services:
  - type: web
    name: fontmikke
    env: ruby
    plan: free
    region: singapore
    branch: main

    buildCommand: |
      gem install bundler -v 2.4.22
      bundle install
      bin/rails tailwindcss:build
      bundle exec rake assets:precompile
      bundle exec rake assets:clean
      echo "=== マイグレーション開始 ==="
      bin/rails db:migrate
      echo "=== マイグレーション完了 ==="
      echo "=== Seed実行開始 ==="
      bin/rails db:seed
      echo "=== Seed実行完了 ==="
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}

    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        sync: false
