services:
  - type: web
    name: fontmikke
    env: ruby
    plan: free
    region: singapore
    branch: main

    buildCommand: "./bin/render-build.sh"

    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}

    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: fontmikke-database
          property: connectionString

databases:
  - name: fontmikke-database
    databaseName: fontmikke_production
    user: fontmikke_user
    region: singapore