services:
  - type: web
    name: fontmikke
    env: docker
    plan: free
    region: singapore
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fontmikke-db
          property: connectionString
