default: &default
  adapter: postgresql
  encoding: unicode
  username: naofumi
  password: password
  pool: 5

development:
  <<: *default
  database: fontmikke_development

test:
  <<: *default
  database: myapp_test

production:
  url: <%= ENV['DATABASE_URL'] %>
